// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type LogEntry struct {
	ID            uuid.UUID       `json:"id"`
	Timestamp     time.Time       `json:"timestamp"`
	Level         string          `json:"level"`
	Service       string          `json:"service"`
	Module        string          `json:"module"`
	CorrelationID string          `json:"correlation_id"`
	Message       string          `json:"message"`
	Attrs         json.RawMessage `json:"attrs"`
}
