// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	CountLogs(ctx context.Context, arg CountLogsParams) (int64, error)
	DeleteOldLogs(ctx context.Context, timestamp time.Time) error
	InsertLog(ctx context.Context, arg InsertLogParams) error
	QueryLogs(ctx context.Context, arg QueryLogsParams) ([]LogEntry, error)
}

var _ Querier = (*Queries)(nil)
