// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const countLogs = `-- name: CountLogs :one
SELECT COUNT(*) FROM log.entries
WHERE
    ($1::text = '' OR service = $1) AND
    ($2::text = '' OR level = $2) AND
    ($3::text = '' OR correlation_id = $3)
`

type CountLogsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) CountLogs(ctx context.Context, arg CountLogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLogs, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldLogs = `-- name: DeleteOldLogs :exec
DELETE FROM log.entries WHERE timestamp < $1
`

func (q *Queries) DeleteOldLogs(ctx context.Context, timestamp time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldLogs, timestamp)
	return err
}

const insertLog = `-- name: InsertLog :exec
INSERT INTO log.entries (timestamp, level, service, module, correlation_id, message, attrs)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertLogParams struct {
	Timestamp     time.Time       `json:"timestamp"`
	Level         string          `json:"level"`
	Service       string          `json:"service"`
	Module        string          `json:"module"`
	CorrelationID string          `json:"correlation_id"`
	Message       string          `json:"message"`
	Attrs         json.RawMessage `json:"attrs"`
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) error {
	_, err := q.db.ExecContext(ctx, insertLog,
		arg.Timestamp,
		arg.Level,
		arg.Service,
		arg.Module,
		arg.CorrelationID,
		arg.Message,
		arg.Attrs,
	)
	return err
}

const queryLogs = `-- name: QueryLogs :many
SELECT id, timestamp, level, service, module, correlation_id, message, attrs FROM log.entries
WHERE
    ($1::text = '' OR service = $1) AND
    ($2::text = '' OR level = $2) AND
    ($3::text = '' OR correlation_id = $3)
ORDER BY timestamp DESC
LIMIT $4 OFFSET $5
`

type QueryLogsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) QueryLogs(ctx context.Context, arg QueryLogsParams) ([]LogEntry, error) {
	rows, err := q.db.QueryContext(ctx, queryLogs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogEntry{}
	for rows.Next() {
		var i LogEntry
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Level,
			&i.Service,
			&i.Module,
			&i.CorrelationID,
			&i.Message,
			&i.Attrs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
