// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: log/v1/log.proto

package logv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogRecord is published to log.ingest (fire-and-forget)
type LogRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Module        string                 `protobuf:"bytes,4,opt,name=module,proto3" json:"module,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Attrs         []byte                 `protobuf:"bytes,7,opt,name=attrs,proto3" json:"attrs,omitempty"` // JSON blob
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_log_v1_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_log_v1_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_log_v1_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogRecord) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogRecord) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRecord) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogRecord) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *LogRecord) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *LogRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRecord) GetAttrs() []byte {
	if x != nil {
		return x.Attrs
	}
	return nil
}

// QueryLogsRequest is sent to log.query (request/reply)
type QueryLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLogsRequest) Reset() {
	*x = QueryLogsRequest{}
	mi := &file_log_v1_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogsRequest) ProtoMessage() {}

func (x *QueryLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_v1_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogsRequest.ProtoReflect.Descriptor instead.
func (*QueryLogsRequest) Descriptor() ([]byte, []int) {
	return file_log_v1_log_proto_rawDescGZIP(), []int{1}
}

func (x *QueryLogsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *QueryLogsRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *QueryLogsRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *QueryLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type QueryLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogRecord           `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLogsResponse) Reset() {
	*x = QueryLogsResponse{}
	mi := &file_log_v1_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogsResponse) ProtoMessage() {}

func (x *QueryLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_v1_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogsResponse.ProtoReflect.Descriptor instead.
func (*QueryLogsResponse) Descriptor() ([]byte, []int) {
	return file_log_v1_log_proto_rawDescGZIP(), []int{2}
}

func (x *QueryLogsResponse) GetLogs() []*LogRecord {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *QueryLogsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_log_v1_log_proto protoreflect.FileDescriptor

const file_log_v1_log_proto_rawDesc = "" +
	"\n" +
	"\x10log/v1/log.proto\x12\x06log.v1\"\xc8\x01\n" +
	"\tLogRecord\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x16\n" +
	"\x06module\x18\x04 \x01(\tR\x06module\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x14\n" +
	"\x05attrs\x18\a \x01(\fR\x05attrs\"\x97\x01\n" +
	"\x10QueryLogsRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"P\n" +
	"\x11QueryLogsResponse\x12%\n" +
	"\x04logs\x18\x01 \x03(\v2\x11.log.v1.LogRecordR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05totalB(Z&platform/libs/proto-stubs/log/v1;logv1b\x06proto3"

var (
	file_log_v1_log_proto_rawDescOnce sync.Once
	file_log_v1_log_proto_rawDescData []byte
)

func file_log_v1_log_proto_rawDescGZIP() []byte {
	file_log_v1_log_proto_rawDescOnce.Do(func() {
		file_log_v1_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_log_v1_log_proto_rawDesc), len(file_log_v1_log_proto_rawDesc)))
	})
	return file_log_v1_log_proto_rawDescData
}

var file_log_v1_log_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_log_v1_log_proto_goTypes = []any{
	(*LogRecord)(nil),         // 0: log.v1.LogRecord
	(*QueryLogsRequest)(nil),  // 1: log.v1.QueryLogsRequest
	(*QueryLogsResponse)(nil), // 2: log.v1.QueryLogsResponse
}
var file_log_v1_log_proto_depIdxs = []int32{
	0, // 0: log.v1.QueryLogsResponse.logs:type_name -> log.v1.LogRecord
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_log_v1_log_proto_init() }
func file_log_v1_log_proto_init() {
	if File_log_v1_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_log_v1_log_proto_rawDesc), len(file_log_v1_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_log_v1_log_proto_goTypes,
		DependencyIndexes: file_log_v1_log_proto_depIdxs,
		MessageInfos:      file_log_v1_log_proto_msgTypes,
	}.Build()
	File_log_v1_log_proto = out.File
	file_log_v1_log_proto_goTypes = nil
	file_log_v1_log_proto_depIdxs = nil
}
