// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// ITEMS
	CreateItem(ctx context.Context, arg CreateItemParams) (TodoItem, error)
	// LISTS
	CreateList(ctx context.Context, arg CreateListParams) (TodoList, error)
	DeleteItem(ctx context.Context, arg DeleteItemParams) (uuid.UUID, error)
	DeleteList(ctx context.Context, arg DeleteListParams) (uuid.UUID, error)
	GetAllItemsFromList(ctx context.Context, arg GetAllItemsFromListParams) ([]TodoItem, error)
	GetListsByUser(ctx context.Context, userID uuid.UUID) ([]GetListsByUserRow, error)
	ToggleItemCompleted(ctx context.Context, arg ToggleItemCompletedParams) (TodoItem, error)
	UpdateListTitle(ctx context.Context, arg UpdateListTitleParams) (TodoList, error)
}

var _ Querier = (*Queries)(nil)
