// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :one

INSERT INTO todo.items (list_id, title)
SELECT $1, $2
FROM todo.lists
WHERE id = $1 AND user_id = $3
RETURNING id, list_id, title, completed, created_at, updated_at
`

type CreateItemParams struct {
	ListID uuid.UUID `json:"list_id"`
	Title  string    `json:"title"`
	UserID uuid.UUID `json:"user_id"`
}

// ITEMS
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (TodoItem, error) {
	row := q.db.QueryRowContext(ctx, createItem, arg.ListID, arg.Title, arg.UserID)
	var i TodoItem
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createList = `-- name: CreateList :one

INSERT INTO todo.lists (user_id, title)
VALUES ($1, $2)
RETURNING id, user_id, title, created_at, updated_at
`

type CreateListParams struct {
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
}

// LISTS
func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (TodoList, error) {
	row := q.db.QueryRowContext(ctx, createList, arg.UserID, arg.Title)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :one
DELETE FROM todo.items i
USING todo.lists l
WHERE i.id = $1 AND i.list_id = l.id AND l.user_id = $2
RETURNING i.id
`

type DeleteItemParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteItem, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteList = `-- name: DeleteList :one
DELETE FROM todo.lists
WHERE id = $1 AND user_id = $2
RETURNING id
`

type DeleteListParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteList(ctx context.Context, arg DeleteListParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteList, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAllItemsFromList = `-- name: GetAllItemsFromList :many
SELECT i.id, i.list_id, i.title, i.completed, i.created_at, i.updated_at FROM todo.items i
INNER JOIN todo.lists l ON i.list_id = l.id
WHERE i.list_id = $1 AND l.user_id = $2
ORDER BY i.created_at
`

type GetAllItemsFromListParams struct {
	ListID uuid.UUID `json:"list_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetAllItemsFromList(ctx context.Context, arg GetAllItemsFromListParams) ([]TodoItem, error) {
	rows, err := q.db.QueryContext(ctx, getAllItemsFromList, arg.ListID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoItem{}
	for rows.Next() {
		var i TodoItem
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.Title,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListsByUser = `-- name: GetListsByUser :many
SELECT id, user_id, title, created_at, updated_at FROM todo.lists
WHERE user_id = $1
ORDER BY title
`

func (q *Queries) GetListsByUser(ctx context.Context, userID uuid.UUID) ([]TodoList, error) {
	rows, err := q.db.QueryContext(ctx, getListsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoList{}
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleItemCompleted = `-- name: ToggleItemCompleted :one
UPDATE todo.items i
SET
    completed = NOT completed,
    updated_at = NOW()
FROM todo.lists l
WHERE i.id = $1 AND i.list_id = l.id AND l.user_id = $2
RETURNING i.id, i.list_id, i.title, i.completed, i.created_at, i.updated_at
`

type ToggleItemCompletedParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ToggleItemCompleted(ctx context.Context, arg ToggleItemCompletedParams) (TodoItem, error) {
	row := q.db.QueryRowContext(ctx, toggleItemCompleted, arg.ID, arg.UserID)
	var i TodoItem
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateListTitle = `-- name: UpdateListTitle :one
UPDATE todo.lists
SET
    title = $3,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, created_at, updated_at
`

type UpdateListTitleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
}

func (q *Queries) UpdateListTitle(ctx context.Context, arg UpdateListTitleParams) (TodoList, error) {
	row := q.db.QueryRowContext(ctx, updateListTitle, arg.ID, arg.UserID, arg.Title)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
