// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: todo/v1/todo.proto

package todov1

import (
	_ "github.com/terjelafton/platform/libs/proto-stubs/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type List struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TotalItems     int32                  `protobuf:"varint,6,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	CompletedItems int32                  `protobuf:"varint,7,opt,name=completed_items,json=completedItems,proto3" json:"completed_items,omitempty"`
	OwnerName      string                 `protobuf:"bytes,8,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	IsOwner        bool                   `protobuf:"varint,9,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *List) Reset() {
	*x = List{}
	mi := &file_todo_v1_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{0}
}

func (x *List) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *List) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *List) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *List) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *List) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *List) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *List) GetCompletedItems() int32 {
	if x != nil {
		return x.CompletedItems
	}
	return 0
}

func (x *List) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *List) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ListId        string                 `protobuf:"bytes,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Completed     bool                   `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_todo_v1_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *Item) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Item) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListRequest) Reset() {
	*x = CreateListRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListRequest) ProtoMessage() {}

func (x *CreateListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListRequest.ProtoReflect.Descriptor instead.
func (*CreateListRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{2}
}

func (x *CreateListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateListRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *List                  `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListResponse) Reset() {
	*x = CreateListResponse{}
	mi := &file_todo_v1_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListResponse) ProtoMessage() {}

func (x *CreateListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListResponse.ProtoReflect.Descriptor instead.
func (*CreateListResponse) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{3}
}

func (x *CreateListResponse) GetList() *List {
	if x != nil {
		return x.List
	}
	return nil
}

type GetListsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListsByUserRequest) Reset() {
	*x = GetListsByUserRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListsByUserRequest) ProtoMessage() {}

func (x *GetListsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetListsByUserRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{4}
}

func (x *GetListsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetListsByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lists         []*List                `protobuf:"bytes,1,rep,name=lists,proto3" json:"lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListsByUserResponse) Reset() {
	*x = GetListsByUserResponse{}
	mi := &file_todo_v1_todo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListsByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListsByUserResponse) ProtoMessage() {}

func (x *GetListsByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListsByUserResponse.ProtoReflect.Descriptor instead.
func (*GetListsByUserResponse) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{5}
}

func (x *GetListsByUserResponse) GetLists() []*List {
	if x != nil {
		return x.Lists
	}
	return nil
}

type UpdateListTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateListTitleRequest) Reset() {
	*x = UpdateListTitleRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateListTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateListTitleRequest) ProtoMessage() {}

func (x *UpdateListTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateListTitleRequest.ProtoReflect.Descriptor instead.
func (*UpdateListTitleRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateListTitleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateListTitleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateListTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UpdateListTitleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *List                  `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateListTitleResponse) Reset() {
	*x = UpdateListTitleResponse{}
	mi := &file_todo_v1_todo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateListTitleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateListTitleResponse) ProtoMessage() {}

func (x *UpdateListTitleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateListTitleResponse.ProtoReflect.Descriptor instead.
func (*UpdateListTitleResponse) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateListTitleResponse) GetList() *List {
	if x != nil {
		return x.List
	}
	return nil
}

type DeleteListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListRequest) Reset() {
	*x = DeleteListRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListRequest) ProtoMessage() {}

func (x *DeleteListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListRequest.ProtoReflect.Descriptor instead.
func (*DeleteListRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListResponse) Reset() {
	*x = DeleteListResponse{}
	mi := &file_todo_v1_todo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListResponse) ProtoMessage() {}

func (x *DeleteListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListResponse.ProtoReflect.Descriptor instead.
func (*DeleteListResponse) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{9}
}

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListId        string                 `protobuf:"bytes,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{10}
}

func (x *CreateItemRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *CreateItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_todo_v1_todo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{11}
}

func (x *CreateItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetAllItemsFromListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListId        string                 `protobuf:"bytes,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllItemsFromListRequest) Reset() {
	*x = GetAllItemsFromListRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllItemsFromListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemsFromListRequest) ProtoMessage() {}

func (x *GetAllItemsFromListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemsFromListRequest.ProtoReflect.Descriptor instead.
func (*GetAllItemsFromListRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllItemsFromListRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *GetAllItemsFromListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAllItemsFromListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllItemsFromListResponse) Reset() {
	*x = GetAllItemsFromListResponse{}
	mi := &file_todo_v1_todo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllItemsFromListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemsFromListResponse) ProtoMessage() {}

func (x *GetAllItemsFromListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemsFromListResponse.ProtoReflect.Descriptor instead.
func (*GetAllItemsFromListResponse) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{13}
}

func (x *GetAllItemsFromListResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ToggleItemCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleItemCompletedRequest) Reset() {
	*x = ToggleItemCompletedRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleItemCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleItemCompletedRequest) ProtoMessage() {}

func (x *ToggleItemCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleItemCompletedRequest.ProtoReflect.Descriptor instead.
func (*ToggleItemCompletedRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{14}
}

func (x *ToggleItemCompletedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToggleItemCompletedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ToggleItemCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleItemCompletedResponse) Reset() {
	*x = ToggleItemCompletedResponse{}
	mi := &file_todo_v1_todo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleItemCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleItemCompletedResponse) ProtoMessage() {}

func (x *ToggleItemCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleItemCompletedResponse.ProtoReflect.Descriptor instead.
func (*ToggleItemCompletedResponse) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{15}
}

func (x *ToggleItemCompletedResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ListId        string                 `protobuf:"bytes,3,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteItemRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

type DeleteItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	mi := &file_todo_v1_todo_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{17}
}

type ListCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *List                  `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCreatedEvent) Reset() {
	*x = ListCreatedEvent{}
	mi := &file_todo_v1_todo_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCreatedEvent) ProtoMessage() {}

func (x *ListCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCreatedEvent.ProtoReflect.Descriptor instead.
func (*ListCreatedEvent) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{18}
}

func (x *ListCreatedEvent) GetList() *List {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListCreatedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type ItemCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemCompletedEvent) Reset() {
	*x = ItemCompletedEvent{}
	mi := &file_todo_v1_todo_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCompletedEvent) ProtoMessage() {}

func (x *ItemCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCompletedEvent.ProtoReflect.Descriptor instead.
func (*ItemCompletedEvent) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{19}
}

func (x *ItemCompletedEvent) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ItemCompletedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type ItemDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListId        string                 `protobuf:"bytes,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemDeletedEvent) Reset() {
	*x = ItemDeletedEvent{}
	mi := &file_todo_v1_todo_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDeletedEvent) ProtoMessage() {}

func (x *ItemDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDeletedEvent.ProtoReflect.Descriptor instead.
func (*ItemDeletedEvent) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{20}
}

func (x *ItemDeletedEvent) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *ItemDeletedEvent) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type ListMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AddedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMember) Reset() {
	*x = ListMember{}
	mi := &file_todo_v1_todo_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMember) ProtoMessage() {}

func (x *ListMember) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMember.ProtoReflect.Descriptor instead.
func (*ListMember) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{21}
}

func (x *ListMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListMember) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ListMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListMember) GetAddedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AddedAt
	}
	return nil
}

type AddListMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListId        string                 `protobuf:"bytes,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MemberEmail   string                 `protobuf:"bytes,3,opt,name=member_email,json=memberEmail,proto3" json:"member_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddListMemberRequest) Reset() {
	*x = AddListMemberRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddListMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddListMemberRequest) ProtoMessage() {}

func (x *AddListMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddListMemberRequest.ProtoReflect.Descriptor instead.
func (*AddListMemberRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{22}
}

func (x *AddListMemberRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *AddListMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddListMemberRequest) GetMemberEmail() string {
	if x != nil {
		return x.MemberEmail
	}
	return ""
}

type AddListMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *ListMember            `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddListMemberResponse) Reset() {
	*x = AddListMemberResponse{}
	mi := &file_todo_v1_todo_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddListMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddListMemberResponse) ProtoMessage() {}

func (x *AddListMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddListMemberResponse.ProtoReflect.Descriptor instead.
func (*AddListMemberResponse) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{23}
}

func (x *AddListMemberResponse) GetMember() *ListMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type RemoveListMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListId        string                 `protobuf:"bytes,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MemberUserId  string                 `protobuf:"bytes,3,opt,name=member_user_id,json=memberUserId,proto3" json:"member_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveListMemberRequest) Reset() {
	*x = RemoveListMemberRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveListMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveListMemberRequest) ProtoMessage() {}

func (x *RemoveListMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveListMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveListMemberRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveListMemberRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *RemoveListMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveListMemberRequest) GetMemberUserId() string {
	if x != nil {
		return x.MemberUserId
	}
	return ""
}

type RemoveListMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveListMemberResponse) Reset() {
	*x = RemoveListMemberResponse{}
	mi := &file_todo_v1_todo_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveListMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveListMemberResponse) ProtoMessage() {}

func (x *RemoveListMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveListMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveListMemberResponse) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{25}
}

type GetListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListId        string                 `protobuf:"bytes,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListMembersRequest) Reset() {
	*x = GetListMembersRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListMembersRequest) ProtoMessage() {}

func (x *GetListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListMembersRequest.ProtoReflect.Descriptor instead.
func (*GetListMembersRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{26}
}

func (x *GetListMembersRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *GetListMembersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*ListMember          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListMembersResponse) Reset() {
	*x = GetListMembersResponse{}
	mi := &file_todo_v1_todo_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListMembersResponse) ProtoMessage() {}

func (x *GetListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListMembersResponse.ProtoReflect.Descriptor instead.
func (*GetListMembersResponse) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{27}
}

func (x *GetListMembersResponse) GetMembers() []*ListMember {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_todo_v1_todo_proto protoreflect.FileDescriptor

const file_todo_v1_todo_proto_rawDesc = "" +
	"\n" +
	"\x12todo/v1/todo.proto\x12\atodo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16common/v1/common.proto\"\xbf\x02\n" +
	"\x04List\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vtotal_items\x18\x06 \x01(\x05R\n" +
	"totalItems\x12'\n" +
	"\x0fcompleted_items\x18\a \x01(\x05R\x0ecompletedItems\x12\x1d\n" +
	"\n" +
	"owner_name\x18\b \x01(\tR\townerName\x12\x19\n" +
	"\bis_owner\x18\t \x01(\bR\aisOwner\"\xd9\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\alist_id\x18\x02 \x01(\tR\x06listId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1c\n" +
	"\tcompleted\x18\x04 \x01(\bR\tcompleted\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"B\n" +
	"\x11CreateListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"7\n" +
	"\x12CreateListResponse\x12!\n" +
	"\x04list\x18\x01 \x01(\v2\r.todo.v1.ListR\x04list\"0\n" +
	"\x15GetListsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"=\n" +
	"\x16GetListsByUserResponse\x12#\n" +
	"\x05lists\x18\x01 \x03(\v2\r.todo.v1.ListR\x05lists\"W\n" +
	"\x16UpdateListTitleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"<\n" +
	"\x17UpdateListTitleResponse\x12!\n" +
	"\x04list\x18\x01 \x01(\v2\r.todo.v1.ListR\x04list\"<\n" +
	"\x11DeleteListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x14\n" +
	"\x12DeleteListResponse\"[\n" +
	"\x11CreateItemRequest\x12\x17\n" +
	"\alist_id\x18\x01 \x01(\tR\x06listId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"7\n" +
	"\x12CreateItemResponse\x12!\n" +
	"\x04item\x18\x01 \x01(\v2\r.todo.v1.ItemR\x04item\"N\n" +
	"\x1aGetAllItemsFromListRequest\x12\x17\n" +
	"\alist_id\x18\x01 \x01(\tR\x06listId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"B\n" +
	"\x1bGetAllItemsFromListResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.todo.v1.ItemR\x05items\"E\n" +
	"\x1aToggleItemCompletedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"@\n" +
	"\x1bToggleItemCompletedResponse\x12!\n" +
	"\x04item\x18\x01 \x01(\v2\r.todo.v1.ItemR\x04item\"U\n" +
	"\x11DeleteItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\alist_id\x18\x03 \x01(\tR\x06listId\"\x14\n" +
	"\x12DeleteItemResponse\"r\n" +
	"\x10ListCreatedEvent\x12!\n" +
	"\x04list\x18\x01 \x01(\v2\r.todo.v1.ListR\x04list\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"t\n" +
	"\x12ItemCompletedEvent\x12!\n" +
	"\x04item\x18\x01 \x01(\v2\r.todo.v1.ItemR\x04item\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"D\n" +
	"\x10ItemDeletedEvent\x12\x17\n" +
	"\alist_id\x18\x01 \x01(\tR\x06listId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\"\x86\x01\n" +
	"\n" +
	"ListMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x125\n" +
	"\badded_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aaddedAt\"k\n" +
	"\x14AddListMemberRequest\x12\x17\n" +
	"\alist_id\x18\x01 \x01(\tR\x06listId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fmember_email\x18\x03 \x01(\tR\vmemberEmail\"D\n" +
	"\x15AddListMemberResponse\x12+\n" +
	"\x06member\x18\x01 \x01(\v2\x13.todo.v1.ListMemberR\x06member\"q\n" +
	"\x17RemoveListMemberRequest\x12\x17\n" +
	"\alist_id\x18\x01 \x01(\tR\x06listId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12$\n" +
	"\x0emember_user_id\x18\x03 \x01(\tR\fmemberUserId\"\x1a\n" +
	"\x18RemoveListMemberResponse\"I\n" +
	"\x15GetListMembersRequest\x12\x17\n" +
	"\alist_id\x18\x01 \x01(\tR\x06listId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"G\n" +
	"\x16GetListMembersResponse\x12-\n" +
	"\amembers\x18\x01 \x03(\v2\x13.todo.v1.ListMemberR\amembersB*Z(platform/libs/proto-stubs/todo/v1;todov1b\x06proto3"

var (
	file_todo_v1_todo_proto_rawDescOnce sync.Once
	file_todo_v1_todo_proto_rawDescData []byte
)

func file_todo_v1_todo_proto_rawDescGZIP() []byte {
	file_todo_v1_todo_proto_rawDescOnce.Do(func() {
		file_todo_v1_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todo_v1_todo_proto_rawDesc), len(file_todo_v1_todo_proto_rawDesc)))
	})
	return file_todo_v1_todo_proto_rawDescData
}

var file_todo_v1_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_todo_v1_todo_proto_goTypes = []any{
	(*List)(nil),                        // 0: todo.v1.List
	(*Item)(nil),                        // 1: todo.v1.Item
	(*CreateListRequest)(nil),           // 2: todo.v1.CreateListRequest
	(*CreateListResponse)(nil),          // 3: todo.v1.CreateListResponse
	(*GetListsByUserRequest)(nil),       // 4: todo.v1.GetListsByUserRequest
	(*GetListsByUserResponse)(nil),      // 5: todo.v1.GetListsByUserResponse
	(*UpdateListTitleRequest)(nil),      // 6: todo.v1.UpdateListTitleRequest
	(*UpdateListTitleResponse)(nil),     // 7: todo.v1.UpdateListTitleResponse
	(*DeleteListRequest)(nil),           // 8: todo.v1.DeleteListRequest
	(*DeleteListResponse)(nil),          // 9: todo.v1.DeleteListResponse
	(*CreateItemRequest)(nil),           // 10: todo.v1.CreateItemRequest
	(*CreateItemResponse)(nil),          // 11: todo.v1.CreateItemResponse
	(*GetAllItemsFromListRequest)(nil),  // 12: todo.v1.GetAllItemsFromListRequest
	(*GetAllItemsFromListResponse)(nil), // 13: todo.v1.GetAllItemsFromListResponse
	(*ToggleItemCompletedRequest)(nil),  // 14: todo.v1.ToggleItemCompletedRequest
	(*ToggleItemCompletedResponse)(nil), // 15: todo.v1.ToggleItemCompletedResponse
	(*DeleteItemRequest)(nil),           // 16: todo.v1.DeleteItemRequest
	(*DeleteItemResponse)(nil),          // 17: todo.v1.DeleteItemResponse
	(*ListCreatedEvent)(nil),            // 18: todo.v1.ListCreatedEvent
	(*ItemCompletedEvent)(nil),          // 19: todo.v1.ItemCompletedEvent
	(*ItemDeletedEvent)(nil),            // 20: todo.v1.ItemDeletedEvent
	(*ListMember)(nil),                  // 21: todo.v1.ListMember
	(*AddListMemberRequest)(nil),        // 22: todo.v1.AddListMemberRequest
	(*AddListMemberResponse)(nil),       // 23: todo.v1.AddListMemberResponse
	(*RemoveListMemberRequest)(nil),     // 24: todo.v1.RemoveListMemberRequest
	(*RemoveListMemberResponse)(nil),    // 25: todo.v1.RemoveListMemberResponse
	(*GetListMembersRequest)(nil),       // 26: todo.v1.GetListMembersRequest
	(*GetListMembersResponse)(nil),      // 27: todo.v1.GetListMembersResponse
	(*timestamppb.Timestamp)(nil),       // 28: google.protobuf.Timestamp
}
var file_todo_v1_todo_proto_depIdxs = []int32{
	28, // 0: todo.v1.List.created_at:type_name -> google.protobuf.Timestamp
	28, // 1: todo.v1.List.updated_at:type_name -> google.protobuf.Timestamp
	28, // 2: todo.v1.Item.created_at:type_name -> google.protobuf.Timestamp
	28, // 3: todo.v1.Item.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: todo.v1.CreateListResponse.list:type_name -> todo.v1.List
	0,  // 5: todo.v1.GetListsByUserResponse.lists:type_name -> todo.v1.List
	0,  // 6: todo.v1.UpdateListTitleResponse.list:type_name -> todo.v1.List
	1,  // 7: todo.v1.CreateItemResponse.item:type_name -> todo.v1.Item
	1,  // 8: todo.v1.GetAllItemsFromListResponse.items:type_name -> todo.v1.Item
	1,  // 9: todo.v1.ToggleItemCompletedResponse.item:type_name -> todo.v1.Item
	0,  // 10: todo.v1.ListCreatedEvent.list:type_name -> todo.v1.List
	28, // 11: todo.v1.ListCreatedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	1,  // 12: todo.v1.ItemCompletedEvent.item:type_name -> todo.v1.Item
	28, // 13: todo.v1.ItemCompletedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	28, // 14: todo.v1.ListMember.added_at:type_name -> google.protobuf.Timestamp
	21, // 15: todo.v1.AddListMemberResponse.member:type_name -> todo.v1.ListMember
	21, // 16: todo.v1.GetListMembersResponse.members:type_name -> todo.v1.ListMember
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_todo_v1_todo_proto_init() }
func file_todo_v1_todo_proto_init() {
	if File_todo_v1_todo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todo_v1_todo_proto_rawDesc), len(file_todo_v1_todo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_todo_v1_todo_proto_goTypes,
		DependencyIndexes: file_todo_v1_todo_proto_depIdxs,
		MessageInfos:      file_todo_v1_todo_proto_msgTypes,
	}.Build()
	File_todo_v1_todo_proto = out.File
	file_todo_v1_todo_proto_goTypes = nil
	file_todo_v1_todo_proto_depIdxs = nil
}
